language: java
jdk:
  - openjdk8
branches:
  only:
    - master
    - develop
env:
  global:
    # Set default environment variable
    - AWS_REGION_DEFAULT=ap-northeast-2
    - DEPLOY_DIR_DEFAULT=deploy

    # If variable set in travis setting, this variable is overridden by travis setting
    - AWS_REGION=${AWS_REGION_VARIABLE:-$AWS_REGION_DEFAULT}
    - DEPLOY_DIR=${DEPLOY_DIR_VARIABLE:-$DEPLOY_DIR_DEFAULT}
    - APP_NAME=mart-holiday-alarm

cache:
    directories:
        - "$HOME/.m2/repository"
        - "$HOME/.gradle"
script: "./gradlew clean build"

before_deploy:
    - echo $AWS_REGION
    - echo $DEPLOY_DIR
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_REPO_SLUG

after_success:
  - ./gradlew jacocoTestReport coveralls