branches:
  only:
    - master
    - develop
env:
  global:
    - AWS_REGION=ap-northeast-2
    - AWS_BUCKET=mart-holiday-alarm
    - GITHUB_REPO=hongsii/travis-ci-deploy-test
before_deploy:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then zip -r master/mart-holiday-alarm *; fi
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then zip -r develop/mart-holiday-alarm *; fi
deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY2"
    secret_access_key: "$AWS_SECRET_KEY2"
    bucket: $AWS_BUCKET
    region: $AWS_REGION
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    upload-dir: master
    on:
      repo: $GITHUB_REPO
      branch: master
  - provider: codedeploy
    access_key_id: "$AWS_ACCESS_KEY2"
    secret_access_key: "$AWS_SECRET_KEY2"
    bucket: $AWS_BUCKET
    region: $AWS_REGION
    key: mart-holiday-alarm.zip
    bundle_type: zip
    application: mart-holiday-alarm
    deployment_group: mart-holiday-alarm-group
    wait-until-deployed: true
    on:
      repo: $GITHUB_REPO
      branch: master
